# Generated by Django 5.2.12 on 2026-03-14 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterydata',
            name='purchase_enabled',
            field=models.BooleanField(default=False, help_text='True only when prediction is successfully completed'),
        ),
        migrations.AlterField(
            model_name='evlisting',
            name='listing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('pending_sale', 'Pending Sale'), ('sold', 'Sold')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='evlisting',
            name='mileage',
            field=models.PositiveIntegerField(help_text='Mileage in km'),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(choices=[('submitted', 'Submitted'), ('admin_review', 'Under Admin Review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='marketplace.evlisting')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
