# Generated by Django 5.2.10 on 2026-04-15 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_batterydata_purchase_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.evlisting'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='request_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('seller_confirmed', 'Seller Confirmed'), ('admin_review', 'Under Admin Review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
