# Generated by Django 5.2.10 on 2026-04-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_message_ev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='request_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('seller_confirmed', 'Seller Confirmed'), ('under_review', 'Under Admin Review'), ('invoice_sent', 'Invoice Sent'), ('payment_submitted', 'Payment Submitted'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
