server {
    listen 80;
    server_name your-domain-or-ip;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        root /home/ubuntu/EVTRUST-A-Predictable-EV-Resale-Marketplace;
    }

    location /media/ {
        root /home/ubuntu/EVTRUST-A-Predictable-EV-Resale-Marketplace;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
